- server/README.md
- server/controllers/TransactionController.js
- server/routes/routes.js
getUserTransactions was not routed properly so the fix was a replacement.
The new controller function is checkBuyerPurchases and the route is "/buyerPurchases" to get the accurate payload.
> fix: user transactions

- server/controllers/getUserBalance.js
@tarzann419 This is just the edit to the destructuring
> fix: simplified code

- server/controllers/CreateAndMintToken.js
- server/models/CollectionModel.js
- server/models/TokenModel.js
@tarzann419 New feature update
> feat: add new minted tokens to collection

- server/controllers/CreateAndMintToken.js
- server/index.js
- server/models/TokenModel.js
- server/utils/attackTokenToItem.js
- server/utils/scheduler.js
@tarzann419 
What I did here is just to build a scheduler first of all for automating the task of attaching winning tokens to an item.
**Todo**: I have to build the algorithm for attaching these tokens to the user when they purchase an item
> feat: attach winning token to an item

- server/controllers/TransferToken.js
- server/index.js
- server/utils/checkWinningUser.js
- server/utils/scheduleWinningUser.js
@tarzann419 This is my final push for the day. 
To explain this; when a user transfers a token that is a winning token to another user, it adds the token to the new wallet's account
I also added a scheduler for checking users with three winning tokens
> feat: add winning token on transfer

- .github/workflows/healthCheck.yml
- node_modules/.bin/tree-kill
- node_modules/.package-lock.json
- node_modules/tree-kill/LICENSE
- node_modules/tree-kill/README.md
- node_modules/tree-kill/cli.js
- node_modules/tree-kill/index.d.ts
- node_modules/tree-kill/index.js
- node_modules/tree-kill/package.json
- package-lock.json
- package.json
- server/.babelrc
- server/db.js
- server/index.js
- server/jest.config.js
- server/package-lock.json
- server/package.json
- server/server.test.js
I've spent my entire lifetime in an alternate universe writing test scripts for the server just incase
@tarzann419
> Run server test

- frontend2/views/admin/items/create_item.ejs
- frontend2/views/auth/login.ejs
- frontend2/views/partials/admin/header.ejs
- server/middleware/checkAuth.js
- server/routes/view.routes.js
One middleware for routes that requires authentication.
What I can't do.
1. Go through all those code to find the style.css responsible for the header
@tarzann419
> fix: middleware for auth

- server/README.md
- server/models/UserModel.js
Still working on these features by referencing to the unique docs cause they don't seem to be a way of having an amount to be transferred for tokens
@tarzann419
> feat: user admin and purchase item

- server/README.md
- server/controllers/ItemsController.js
- server/controllers/TransactionController.js
- server/models/ItemsModel.js
> feat: purchase items with UNQ

- server/README.md
- server/controllers/CreateAndMintToken.js
- server/routes/routes.js
Take note that the route for create collection has been renamed
@tarzann419
> docs: update README and refactor route/controller names for clarity

- server/README.md
- server/controllers/CreateAndMintToken.js
- server/controllers/MarketPlace.js
- server/controllers/TransactionController.js
- server/controllers/UserController.js
- server/controllers/getUserBalance.js
- server/models/CollectionModel.js
- server/models/TokenModel.js
- server/models/UserModel.js
- server/routes/routes.js
@tarzann419 
So alot of changes has been made. Refer to the docs for clarity.
The only thing left right now is swapping of coupons. That may seem very difficult due to the UNQ restrictions for now.
My batteries are all down because of light so this is where I stop till we get light.
> feat: buy a coupon and transfer all ownership

- frontend2/views/admin/items/create_item.ejs
- frontend2/views/auth/register.ejs
- frontend2/views/collection/create_collection.ejs
- frontend2/views/collection/my-collections.ejs
- frontend2/views/collection/tokens/all_tokens.ejs
- frontend2/views/items/shop.ejs
- frontend2/views/partials/admin/sidebar.ejs
- server/controllers/CreateAndMintToken.js
- server/controllers/MarketPlace.js
- server/routes/routes.js
worked on the apis provided. everything seems smooth; for now. you can spin it and let me know what you think @Daniel-16 
TODO: burn tokens
> update: coupon features reconfig

- server/README.md
- server/controllers/CreateAndMintToken.js
- server/controllers/MarketPlace.js
- server/controllers/TransactionController.js
- server/controllers/getUserBalance.js
- server/models/TokenModel.js
- server/routes/routes.js
@tarzann419 
Store owners can now set number of quantity of an item
Marketplace only returns items that are still available
> feat: set number of quantity available for purchase

- server/controllers/CreateAndMintToken.js
- server/controllers/MarketPlace.js
- server/utils/checkWinningUser.js
- server/utils/scheduler.js
@tarzann419 
Note some change in routes.
Also marketplace only returns purchasable tokens.
Winning tokens are hidden for now. 
Would continue later in the day
> feat: Store to specify win token

- server/README.md
- server/controllers/CreateAndMintToken.js
- server/controllers/TransactionController.js
- server/models/SpecialToken.js
- server/models/TokenModel.js
- server/models/TransactionModel.js
- server/routes/routes.js
@tarzann419 
Store owners are to create a store and when a user purchases over 2 items from that store, the user gets a special token
**Bug to fix**: Function to track user purchases correctly.
> feat: create winning token

- server/README.md
- server/controllers/CreateAndMintToken.js
- server/controllers/MarketPlace.js
- server/controllers/TransactionController.js
- server/models/SpecialToken.js
- server/models/TokenModel.js
A few changes were made.
Creating special tokens now has a price attached.
When a store creates an item, they can specify if it's an actual item or a coupon. So you might have to change some things on the frontend to implement that.
Marketplace only returns coupons.
Stores returns both coupons and items created by that store.
I also tested what you did last night and it works like magic.
@tarzann419
> feat: purchase item

- server/README.md
- server/controllers/CreateAndMintToken.js
- server/controllers/RedeemCoupons.js
- server/controllers/TransactionController.js
- server/helper/BurnToken.js
- server/models/RedeemModel.js
- server/models/SpecialToken.js
- server/models/TokenModel.js
- server/routes/routes.js
This is the new feature update for redeeming coupons.
How it works:
- Create a redeem coupon request.
- Store sees redeem request and can choose to accept or decline.
- If accepted, DB would update the status and burn the token as well as delete from the DB.
Also, note the changes to differentiate coupons from actual items.
@tarzann419
> feat: implement coupon redemption functionality

- server/README.md
- server/controllers/TransactionController.js
- server/models/TransactionModel.js
- server/services/SpecialTokenService.js
- server/utils/UseCoupon.js
- server/utils/attackTokenToItem.js
- server/utils/scheduler.js
@tarzann419 
Changes were made and the discount works but some considerations are required (burning it after being applied).
Docs were updated for clarity based on how you stated initially.
> Implement coupon discount and special token transfer in purchase process

- server/controllers/TransactionController.js
- server/controllers/UserController.js
- server/models/UserModel.js
- server/utils/dailyPoints.js
@tarzann419 Reward system finally works as expected
> feat: reward system

- frontend2/views/admin/dashboard-main.ejs
- server/controllers/SwapCoupons.js
@tarzann419 
Reward points for successfully swapping coupon
Dashboard returns gained points and info
> feat: points for swap

- server/controllers/CreateAndMintToken.js
- server/utils/currencyConverter.js
> feat: convert usd to unq

- server/controllers/TransactionController.js
@tarzann419 
Mirroring account wallet address now works.
Todo: 
Friendly animated loader on purchase
> patch: mirroring wallet addresses
